Portfolio: finish mobile version
pulgosodog/Portfolio-setup-and-mobile-first pull request #2
Opened 2023-04-01 04:14 UTC by pulgosodog

Added "Works", "About me", "Contact me" and "Footer" sections.

2023-04-01 22:42 UTC, OyePriscilla requested changes
Hi @pulgosodog 👍 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Linters check passed ✔️ 
Displayed the project section with CSS flex property ✔️


## Required Changes ♻️

- [ ] Please fix the live demo broken link in the README file, this will ensure that your repo is more engaging. Note: If there is no live demo at the moment, just indicate **Not yet available**. Thanks. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 22:42 UTC, OyePriscilla commented on index.html
>          </button>
- [ ] Please kindly increase the margin-top and margin-bottom of this "down-arrow" and ensure that the other background-image is fixed as well according to the given template. 👍 

## Figma design

<img width="148" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/229316283-af47ec5d-c044-48ff-b374-5219542cf15d.png">

2023-04-01 22:42 UTC, OyePriscilla commented on index.html
> +            <img class="about-left" src="images/illustration- about me- mobile.png" alt="Ilustration">
- [ ] It will be great if you can add this images to your project using CSS background-image properties as pointed out in the previous milestone. 👍

2023-04-01 22:42 UTC, OyePriscilla commented on style.css
> +}
- [ ] Please according to the project requirement kindly ensure that the content of the "About myself" section is aligned with flexbox. 👍

2023-04-01 22:42 UTC, OyePriscilla commented on index.html
> +                alt="Skills: Database Management Version Control CLI Web developmnet PI Design">
- [ ] For good user experience and interaction, kindly ensure to write out the details of these three cards with html. 🙏

2023-04-01 22:42 UTC, OyePriscilla commented on index.html
> +            <form id="survey-form" class="contact-me" action="" method="post">
- [ ] Please kindly remove this form section because it is not part of this milestone, you will be insturcted to implement this in the next milestone. 👍

2023-04-01 22:42 UTC, OyePriscilla commented on index.html
>                      </div>
- [ ] Kindly add button interactions for all your button elements according to the given design. 👍 

## Figma design

<img width="291" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/229319214-bdce2042-7fb9-4bda-bc9c-05da0cb42d3c.png">

2023-04-01 22:51 UTC, pulgosodog commented on style.css
> +}
Hello! This section is position: relative as parent  to get the two vector images inside fixed to the sides with position: absolute to get them out of the flow to not get in the way.

2023-04-02 01:49 UTC, pulgosodog commented on index.html
>          </button>
Done!

2023-04-02 03:20 UTC, pulgosodog commented on index.html
> +            <img class="about-left" src="images/illustration- about me- mobile.png" alt="Ilustration">
I'm not sure how to address this.

2023-04-02 03:21 UTC, pulgosodog commented on style.css
> +}
Addressed!

2023-04-02 03:21 UTC, pulgosodog commented on index.html
> +                alt="Skills: Database Management Version Control CLI Web developmnet PI Design">
Done!

2023-04-02 03:37 UTC, pulgosodog commented on index.html
>                      </div>
Done!

2023-04-02 03:53 UTC, pulgosodog commented on index.html
> +            <form id="survey-form" class="contact-me" action="" method="post">
Done!

2023-04-02 04:35 UTC, binhussen requested changes
Hi @pulgosodog , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 04:35 UTC, binhussen commented on index.html
> +            <img class="about-left" src="images/illustration- about me- mobile.png" alt="Ilustration">
- Kindly, those images are not part of the content (aesthetic reasons), Please update using CSS background images. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info :+1:

2023-04-02 04:35 UTC, binhussen commented on index.html
> +        </div>
- Great job for updating previous reviewer suggestions, however, you added an unnecessary card below your about section, please remove it to stick the Figma design :+1: 
![2023-04-02_07-33](https://user-images.githubusercontent.com/52010789/229331464-0247e446-e9da-4108-b0c1-6d67ba6f645d.png)

2023-04-02 05:35 UTC, pulgosodog commented on index.html
> +            <img class="about-left" src="images/illustration- about me- mobile.png" alt="Ilustration">
Done! Appreciate the information provided.

2023-04-02 05:38 UTC, pulgosodog commented on index.html
> +        </div>
Hey! @binhussen I need help with this one, I do not know where to look fot the extra card mentioned just below the about section.
If futher fix to this is necesary, **next code reviewer** can you contact me on Slack to review this? This is my last code review.

2023-04-02 05:47 UTC, didierganthier approved these changes
Hi @pulgosodog ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-04-02 06:02 UTC, merged